"""Datetype for tg_chat and user Id (string)

Revision ID: ca480684149d
Revises: 0c4cf54603c3
Create Date: 2023-10-17 19:36:22.092379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca480684149d'
down_revision = '0c4cf54603c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.alter_column('tg_user_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.alter_column('tg_chat_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)

    with op.batch_alter_table('place_images', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place_images', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.alter_column('tg_chat_id',
               existing_type=sa.String(length=15),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('tg_user_id',
               existing_type=sa.String(length=15),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
