"""Feedback table added.

Revision ID: ebfe932ee7b7
Revises: 8ff1018dccd7
Create Date: 2023-10-16 17:02:00.877453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebfe932ee7b7'
down_revision = '8ff1018dccd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_username', sa.String(length=255), nullable=True),
    sa.Column('tg_user_id', sa.Integer(), nullable=False),
    sa.Column('tg_chat_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
